# -*- coding: utf-8 -*-
"""Ngân hàng câu hỏi trắc nghiệm — 20 câu/bài, phỏng vấn."""

def Q(q, o0, o1, o2, o3, ans, explain):
    return {"q": q, "options": [o0, o1, o2, o3], "answer": ans, "explain": explain}


LESSONS = [
    {"id": "oop1", "num": "JC1", "module": "Java Core · Phần 1", "title": "OOP Principles", "javaCore": True},
    {"id": "java2", "num": "JC2", "module": "Java Core · Phần 2", "title": "Collections", "javaCore": True},
    {"id": "java34", "num": "JC3", "module": "Java Core · Phần 3–4", "title": "Advanced Java", "javaCore": True},
    {"id": "video1", "num": "1", "module": "PHASE 1", "title": "Manual vs Automation"},
    {"id": "video2", "num": "2", "module": "PHASE 1", "title": "4 Loại Test"},
    {"id": "phase2", "num": "3", "module": "PHASE 2", "title": "Selenium WebDriver"},
    {"id": "phase3", "num": "4", "module": "PHASE 3", "title": "TestNG & POM"},
    {"id": "phase4", "num": "5", "module": "PHASE 4", "title": "Advanced & CI/CD"},
    {"id": "api1", "num": "API1", "module": "API Testing · Buổi 1", "title": "Fundamentals & HTTP", "apiTesting": True},
    {"id": "api2", "num": "API2", "module": "API Testing · Tuần 3-4", "title": "Auth & Security", "apiTesting": True},
    {"id": "api3", "num": "API3", "module": "API Testing · RestAssured", "title": "RestAssured Automation", "apiTesting": True},
]

OOP1 = [
    Q("Trong phỏng vấn Java, Encapsulation được hiểu đúng nhất là gì?",
      "Ẩn implementation, chỉ expose hành vi qua public API có kiểm soát",
      "Gom nhiều class vào một package",
      "Kế thừa toàn bộ method từ class cha",
      "Dùng interface thay cho class", 0,
      "Encapsulation = data hiding + kiểm soát truy cập qua getter/setter/method, không lộ trực tiếp state."),
    Q("Vì sao balance nên private trong class BankAccount?",
      "Để client không gán balance = -999999, phá business rule",
      "Để compiler chạy nhanh hơn",
      "Vì private là mặc định trong Java",
      "Để không cần viết method", 0,
      "Private bảo vệ integrity; thao tác qua deposit/withdraw có validate."),
    Q("Quan hệ 'Dog extends Animal' thể hiện nguyên lý OOP nào?",
      "Inheritance", "Encapsulation", "Polymorphism", "Abstraction", 0,
      "extends = kế thừa thuộc tính/hành vi từ class cha."),
    Q("Khi nào KHÔNG nên dùng Inheritance?",
      "Quan hệ là 'has-a' (composition hợp lý hơn)",
      "Cần reuse code",
      "Class con cần override",
      "Cần đa hình", 0,
      "Inheritance cho 'is-a'; has-a dùng composition."),
    Q("@Override trong Java báo hiệu điều gì cho compiler?",
      "Method con thay thế implementation method cha",
      "Method mới hoàn toàn",
      "Method static",
      "Method final", 0,
      "@Override = override instance method theo contract class cha."),
    Q("Polymorphism runtime (dynamic dispatch) xảy ra khi nào?",
      "Gọi method trên reference cha, object thực tế là con",
      "Khai báo biến kiểu int",
      "Dùng static method",
      "Import package", 0,
      "JVM chọn method theo actual object type lúc runtime."),
    Q("Đoạn: Animal a = new Dog(); a.speak(); — speak() gọi bản nào?",
      "Dog.speak() nếu Dog override", "Animal.speak() luôn luôn",
      "Không compile", "Ngẫu nhiên", 0,
      "Dynamic binding: implementation của Dog được gọi."),
    Q("Abstract class khác Interface (Java 8+) ở điểm nào quan trọng?",
      "Abstract class có thể có concrete method + state; interface chủ yếu contract",
      "Interface luôn có constructor",
      "Abstract class không cho phép kế thừa",
      "Không khác nhau", 0,
      "Abstract class = partial implementation; interface = capability contract."),
    Q("Abstraction giúp test automation như thế nào?",
      "Test code phụ thuộc interface, đổi implementation (DB, driver) dễ",
      "Không cần locator",
      "Không cần wait",
      "Chỉ chạy manual", 0,
      "Abstraction tách contract khỏi implementation — linh hoạt khi đổi MySQL/PostgreSQL driver."),
    Q("protected modifier dùng khi nào?",
      "Subclass/package cần truy cập, nhưng không public ra ngoài",
      "Chỉ trong cùng file",
      "Cho mọi class",
      "Thay cho private", 0,
      "protected = visible cho subclass, ẩn với client bên ngoài."),
    Q("Composition over inheritance nghĩa là gì?",
      "Ưu tiên has-a (chứa object) thay vì is-a khi không chắc hierarchy",
      "Không dùng class",
      "Chỉ dùng interface",
      "Viết một class khổng lồ", 0,
      "Composition giảm coupling, tránh deep inheritance tree."),
    Q("final class trong Java có ý nghĩa gì?",
      "Không thể bị extend", "Không thể instantiate",
      "Không có method", "Tự động abstract", 0,
      "final class = không cho kế thừa (ví dụ String)."),
    Q("Lỗi thiết kế: public List<Card> cards trong domain model — vấn đề?",
      "Client có thể clear/add trực tiếp, phá encapsulation",
      "List không dùng được",
      "Không serialize được",
      "Không OOP", 0,
      "Expose mutable collection public = mất kiểm soát state."),
    Q("Trong interview: '4 trụ cột OOP' — thứ tự trình bày tốt?",
      "Encapsulation → Inheritance → Polymorphism → Abstraction",
      "Chỉ Polymorphism", "Ngẫu nhiên", "Không có thứ tự", 0,
      "Thường bắt từ encapsulation (nền) đến abstraction (thiết kế hệ thống)."),
    Q("Interface với nhiều implementation (MySQL vs Mongo repo) thể hiện?",
      "Polymorphism + Abstraction", "Chỉ Encapsulation",
      "Chỉ Inheritance", "Không liên quan OOP", 0,
      "Repository interface + nhiều impl = đa hình + trừu tượng hóa persistence."),
    Q("Tight coupling là gì và OOP giảm bằng cách nào?",
      "Phụ thuộc chi tiết implementation; giảm bằng abstraction/interface",
      "Viết ít code", "Dùng global variable",
      "Không dùng method", 0,
      "Loose coupling qua interface/encapsulation dễ test và maintain."),
    Q("Method overloading vs overriding — khác biệt cốt lõi?",
      "Overloading: cùng tên, khác signature, compile-time; Overriding: kế thừa, runtime",
      "Giống nhau", "Overloading là runtime",
      "Overriding là compile-time", 0,
      "Overload = static binding; Override = dynamic binding."),
    Q("Khi design class User cho automation framework, field password nên?",
      "private, không log, truy cập qua method an toàn",
      "public để test nhanh",
      "static", "final và public", 0,
      "Bảo mật + encapsulation: không expose credential trong API công khai."),
    Q("LSP (Liskov) liên quan inheritance: class con phải?",
      "Thay thế được class cha mà không phá hành vi mong đợi",
      "Có ít method hơn cha",
      "Không override", "Luôn throw Exception", 0,
      "LSP: subtype phải usable everywhere supertype dùng được — hay hỏi senior."),
    Q("Tại sao OOP quan trọng với Page Object Model?",
      "POM = đóng gói trang/locator; tái sử dụng & bảo trì theo OOP",
      "POM không dùng class",
      "POM chỉ cho manual test",
      "POM thay Selenium", 0,
      "POM áp dụng encapsulation + abstraction cho UI layer."),
]

JAVA2 = [
    Q("ArrayList vs LinkedList — khi nào chọn ArrayList cho test data?",
      "Cần truy cập index/random nhanh, ít insert giữa list",
      "Cần insert đầu list liên tục",
      "Cần unique elements",
      "Cần key-value lookup", 0,
      "ArrayList O(1) get by index; LinkedList tốt cho insert/delete đầu."),
    Q("HashSet đảm bảo điều gì?",
      "Không duplicate, unordered (mặc định)",
      "Thứ tự insertion", "Sorted theo key",
      "Cho phép null nhiều lần", 0,
      "Set = unique; HashSet dùng hash table."),
    Q("Map trong automation: lưu locator name → By object phù hợp vì?",
      "Tra cứu O(1) theo key, mô tả rõ ràng",
      "Giữ thứ tự insert",
      "Cho phép duplicate key",
      "Thay cho List", 0,
      "Map = key-value, ideal cho dictionary locators/results."),
    Q("HashMap vs TreeMap — khi cần keys sorted alphabetically?",
      "TreeMap", "HashMap", "ArrayList", "HashSet", 0,
      "TreeMap = Red-Black tree, keys sorted."),
    Q("list.add(0, x) trên ArrayList có đặc điểm performance?",
      "O(n) do shift elements", "O(1)", "O(log n)",
      "Không hỗ trợ", 0,
      "Insert giữa/cuối ArrayList tốn chi phí dịch phần tử."),
    Q("Khi lưu danh sách test case ID không trùng, collection phù hợp?",
      "Set (HashSet)", "List", "Queue", "Stack", 0,
      "Set đảm bảo uniqueness."),
    Q("ConcurrentModificationException thường gặp khi?",
      "Modify collection while iterating không qua Iterator.remove",
      "Dùng HashMap", "Dùng ArrayList.get",
      "Compile error", 0,
      "Cấu trúc bị đổi trong lúc for-each — dùng Iterator hoặc copy."),
    Q("Map.get(key) trả về null — luôn có nghĩa key không tồn tại?",
      "Không — có thể value thực sự là null",
      "Luôn không tồn tại", "Luôn lỗi",
      "Map không cho null value", 0,
      "containsKey() để phân biệt missing key vs null value."),
    Q("LinkedList implements List và Deque — ứng dụng queue test jobs?",
      "Có — addLast/pollFirst cho FIFO queue",
      "Không — chỉ ArrayList",
      "Chỉ HashSet", "Chỉ TreeMap", 0,
      "Deque interface hỗ trợ queue/stack operations."),
    Q("Collections.sort(list) yêu cầu elements?",
      "Comparable hoặc truyền Comparator",
      "Phải là String", "Phải unique",
      "Phải HashMap", 0,
      "Sort cần cách so sánh — Comparable/Comparator."),
    Q("HashMap internal: collision xử lý (Java 8+) bằng?",
      "Linked list / tree tại bucket khi nhiều key cùng hash",
      "Bỏ qua key trùng", "Copy sang ArrayList",
      "Throw error", 0,
      "Bucket chaining; treeify khi chain dài."),
    Q("Chọn structure lưu kết quả test run: testName → PASS/FAIL?",
      "Map<String, String>", "Set", "Stack",
      "Queue", 0,
      "Map phù hợp key-value results."),
    Q("ArrayList(initialCapacity) lợi ích khi biết trước size?",
      "Giảm resize internal array, tăng performance",
      "Tự động sort", "Unique elements",
      "Thread-safe", 0,
      "Tránh grow nhiều lần khi biết kích thước ước lượng."),
    Q("Immutable list (List.of) lợi ích trong framework?",
      "An toàn, không bị test code sửa nhầm constants",
      "Nhanh hơn ArrayList mutable", "Cho phép null mọi nơi",
      "Tự động thread-safe mọi case", 0,
      "Immutable collections bảo vệ config/constants."),
    Q("contains() trên List complexity?",
      "O(n) linear search", "O(1)", "O(log n)",
      "O(n log n)", 0,
      "List.contains phải duyệt — Set/Map hash O(1) average."),
    Q("PriorityQueue dùng khi automation cần?",
      "Process jobs theo priority (severity, deadline)",
      "Unique elements", "Key-value", "Sorted map keys", 0,
      "PriorityQueue = heap theo comparator."),
    Q("equals() và hashCode() contract cho HashMap key?",
      "Equal objects phải cùng hashCode; cùng hash có thể khác equal",
      "Không liên quan", "Chỉ cần equals",
      "Chỉ cần hashCode", 0,
      "Vi phạm contract gây mất entry trong HashMap."),
    Q("Copy List trước khi iterate để modify an toàn bằng?",
      "new ArrayList<>(original) hoặc List.copyOf",
      "original.clear()", "Collections.reverse",
      "Không thể", 0,
      "Snapshot copy tránh ConcurrentModification."),
    Q("Trong interview: khi nào List, Set, Map?",
      "List: ordered/duplicate; Set: unique; Map: lookup by key",
      "Luôn ArrayList", "Luôn HashMap",
      "Không dùng Collections Framework", 0,
      "Chọn theo semantics dữ liệu, không theo thói quen."),
    Q("Stream API (preview Collections) — forEach trên List test IDs để?",
      "Duyệt functional style; có thể filter/map",
      "Sort only", "Replace HashMap",
      "Compile-time only", 0,
      "Streams xử lý collection declarative — liên kết JC3."),
]

from quiz_content_rest import (  # noqa: E402
    API1,
    API2,
    API3,
    JAVA34,
    PHASE2,
    PHASE3,
    PHASE4,
    VIDEO1,
    VIDEO2,
)

BANKS = {
    "oop1": {"title": "OOP Principles", "questions": OOP1},
    "java2": {"title": "Collections", "questions": JAVA2},
    "java34": {"title": "Advanced Java", "questions": JAVA34},
    "video1": {"title": "Manual vs Automation", "questions": VIDEO1},
    "video2": {"title": "4 Loại Test", "questions": VIDEO2},
    "phase2": {"title": "Selenium WebDriver", "questions": PHASE2},
    "phase3": {"title": "TestNG & POM", "questions": PHASE3},
    "phase4": {"title": "Advanced & CI/CD", "questions": PHASE4},
    "api1": {"title": "Fundamentals & HTTP", "questions": API1},
    "api2": {"title": "Auth & Security", "questions": API2},
    "api3": {"title": "RestAssured Automation", "questions": API3},
}
