# -*- coding: utf-8 -*-
from quiz_content import Q

JAVA34 = [
    Q("finally block chạy khi nào?", "Luôn (trừ System.exit) sau try/catch", "Chỉ khi có exception", "Chỉ khi không exception", "Không bao giờ", 0, "finally dùng đóng resource (driver, file)."),
    Q("checked vs unchecked exception?", "Checked: compile bắt buộc handle; Unchecked: RuntimeException", "Giống nhau", "Unchecked phải throws", "Checked không cần try", 0, "IOException checked; NullPointerException unchecked."),
    Q("try-with-resources yêu cầu resource?", "Implement AutoCloseable", "Extend Thread", "static", "final", 0, "Tự đóng close() — best practice File/Reader/Stream."),
    Q("custom exception nên extend?", "Exception hoặc RuntimeException tùy strategy", "Object", "String", "Thread", 0, "Business exception thường RuntimeException nếu không force catch."),
    Q("Stream filter + map pipeline đọc file lines để?", "Transform/lọc declarative", "Thay for-loop bắt buộc", "Chỉ sort", "Chỉ write file", 0, "Stream = map/filter/collect trên collection."),
    Q("Lambda (x) -> x*2 dùng với?", "Functional interface (một abstract method)", "Mọi class", "static method only", "Constructor", 0, "Lambda = shorthand cho SAM interface."),
    Q("Optional.ofNullable tránh?", "NullPointerException khi chain", "IOException", "Compile error", "Infinite loop", 0, "Optional thể hiện có/không value."),
    Q("Files.readString(path) thuộc?", "java.nio.file modern I/O", "java.applet", "Collections", "Thread", 0, "NIO.2 API đọc file gọn."),
    Q("throw vs throws?", "throw: ném tại chỗ; throws: khai báo method có thể ném", "Giống nhau", "throws ném ngay", "throw chỉ compile", 0, "Phân biệt hay hỏi interview."),
    Q("catch (Exception e) quá rộng — vấn đề?", "Nuốt lỗi cụ thể, khó debug", "Nhanh hơn", "Bắt buộc", "Tốt nhất", 0, "Catch specific trước, Exception cuối nếu cần."),
    Q("parallelStream() rủi ro trong test?", "Race condition, không deterministic", "Luôn nhanh hơn", "Không dùng được", "Chỉ cho List", 0, "Parallel cần thread-safe data."),
    Q("Predicate<T> trong Stream dùng để?", "Test condition filter", "Map transform", "Reduce sum", "Sort", 0, "Predicate = boolean test."),
    Q("BufferedReader giúp?", "Đọc theo buffer, hiệu quả hơn từng byte", "Ghi file", "Network only", "Compile", 0, "Buffer giảm I/O calls."),
    Q("multi-catch catch (A | B e) lợi ích?", "Một block xử lý nhiều type", "Chậm hơn", "Không compile", "Thay throws", 0, "Java 7+ gọn hơn nhiều catch giống nhau."),
    Q("AssertionError vs Exception trong test?", "AssertionError thường từ assert/TestNG assert", "Giống nhau", "Luôn checked", "Không trong Java", 0, "Assert fail = AssertionError/AssertionError tùy framework."),
    Q("String không đổi (immutable) ảnh hưởng?", "An toàn thread; nối nhiều dùng StringBuilder", "Không hash được", "Không equals", "Không dùng được", 0, "Immutable string — dùng builder khi loop concat."),
    Q("collect(Collectors.toList()) sau stream?", "Materialize stream thành List", "Sort in-place", "Filter only", "Close file", 0, "Terminal operation tạo collection."),
    Q("FileNotFoundException thường?", "Checked — phải handle khi đọc file", "Unchecked", "Runtime only", "Không trong Java", 0, "IO checked exception classic."),
    Q("method reference Class::method dùng khi?", "Lambda chỉ gọi một method có sẵn", "Cần loop", "Cần 3+ statements", "Thay class", 0, "Shorthand khi logic đơn giản."),
    Q("try-catch trong @Test nên?", "Tránh — để TestNG/framework báo fail rõ", "Luôn catch Exception pass", "Không bao giờ assert", "Bỏ finally", 0, "Test fail nên qua assertion, không nuốt exception."),
]

VIDEO1 = [
    Q("Automation testing phù hợp khi?", "Regression lớn, stable app, ROI dương dài hạn", "Mọi exploratory test", "UI thay đổi hàng ngày", "Không cần maintain", 0, "Không automate hết — chọn case ổn định, lặp lại."),
    Q("Test Pyramid khuyến nghị tỷ lệ?", "Nhiều unit, ít E2E", "Nhiều E2E, ít unit", "Chỉ manual", "Chỉ API", 0, "Pyramid: unit base rộng, UI E2E đỉnh nhỏ."),
    Q("Flaky test là gì?", "Pass/fail không nhất quán cùng code", "Test chậm", "Test manual", "Test unit", 0, "Flaky = timing/data/env — enemy của CI."),
    Q("ROI automation âm khi nào?", "Maintain script > tiết kiệm thời gian", "Chạy parallel", "Dùng POM", "Dùng CI", 0, "ROI = (manual cost saved) - (automation cost)."),
    Q("Manual testing vẫn cần cho?", "Exploratory, usability, ad-hoc", "Regression 1000 case", "Load test", "Nightly build", 0, "Automation không thay sáng tạo và UX exploration."),
    Q("Record & playback tool hạn chế?", "Script brittle, khó maintain khi UI đổi", "Không chạy được", "Không free", "Không record", 0, "Low-code record thường break khi locator đổi."),
    Q("Definition of Done cho automation story?", "Script + code review + CI green + doc", "Chỉ record video", "Chỉ chạy local", "Không cần assert", 0, "DoD gồm maintainability và CI."),
    Q("Shift-left testing nghĩa là?", "Test sớm hơn trong SDLC (unit, API sớm)", "Test production only", "Chỉ manual", "Chỉ UAT", 0, "Shift-left = phát hiện lỗi sớm, rẻ hơn."),
    Q("Automation engineer vs manual — skill khác?", "Coding, framework, CI; manual: domain, exploration", "Giống hệt", "Manual cần Java bắt buộc", "Automation không cần logic", 0, "Automation = dev-test hybrid."),
    Q("Khi UI unstable, chiến lược?", "API/contract test trước, UI sau khi stable", "Automate hết UI ngay", "Bỏ test", "Chỉ screenshot", 0, "Test layer phù hợp độ ổn định."),
    Q("Smoke suite automation mục tiêu?", "Xác nhận build deployable nhanh", "Full regression", "Performance", "Security scan", 0, "Smoke = critical path ngắn."),
    Q("Maintainability automation phụ thuộc?", "POM, clean code, locator strategy", "Số lượng test nhiều", "Ít comment", "Record only", 0, "Design quan trọng hơn số lượng."),
    Q("False positive trong test?", "Pass nhưng app thực tế lỗi", "Fail đúng", "Timeout", "Skip", 0, "Assert yếu → false positive nguy hiểm."),
    Q("CI chạy automation khi?", "Mỗi commit/PR/nightly theo chiến lược", "Chỉ cuối năm", "Chỉ manual trigger", "Không cần", 0, "CI = fast feedback loop."),
    Q("Data-driven manual vs automation?", "Automation scale data dễ hơn", "Manual luôn nhanh hơn", "Không dùng data", "Chỉ CSV", 0, "Automation + data file = hàng trăm case."),
    Q("Không nên automate 100% vì?", "Một số test không ROI, cần human judgment", "Tool không đủ", "Java không hỗ trợ", "Agile cấm", 0, "100% automation là anti-pattern thường gặp."),
    Q("Version control cho test code?", "Bắt buộc — Git như production code", "Không cần", "Chỉ screenshot", "Chỉ Excel", 0, "Test code là code — cần VCS."),
    Q("Stakeholder cần báo cáo automation?", "Coverage, pass rate, duration, flaky", "Chỉ số dòng code", "Không báo cáo", "Chỉ log console", 0, "Metrics minh bạch giá trị automation."),
    Q("Reusable component trong framework?", "Giảm duplicate, tăng maintain", "Tăng flaky", "Chậm hơn", "Không cần OOP", 0, "Reuse = core engineering practice."),
    Q("Entry criteria chạy automation suite?", "Env stable, data ready, build deploy OK", "Không cần", "Chỉ khi release", "Random", 0, "Precondition rõ — tránh fail mơ hồ."),
]

VIDEO2 = [
    Q("Unit test đặc điểm?", "Cô lập module nhỏ, nhanh, mock dependency", "Cần browser", "Cần DB thật", "Chỉ manual", 0, "Unit = isolated, fast feedback."),
    Q("Integration test kiểm tra?", "Tương tác giữa module/service", "Chỉ một method", "Chỉ UI pixel", "Chỉ document", 0, "Integration = boundary giữa components."),
    Q("E2E test trong web?", "Luồng user thật qua UI (hoặc gần production)", "Chỉ unit", "Chỉ SQL", "Không cần assert", 0, "E2E = full stack user journey."),
    Q("API test thường nhanh hơn UI E2E vì?", "Không render browser, ít flaky", "Không cần assert", "Không cần data", "Luôn manual", 0, "API layer ổn định hơn UI cho regression."),
    Q("Test isolation unit test dùng?", "Mock/stub dependency", "Browser thật", "Production DB", "Không cần", 0, "Mock = kiểm soát behavior dependency."),
    Q("Contract test (API) đảm bảo?", "Consumer/provider thỏa agreement", "UI color", "CPU usage", "Manual only", 0, "Contract = schema/response agreement."),
    Q("Regression suite nên gồm?", "Mix unit + integration + critical E2E", "Chỉ exploratory", "Chỉ một unit test", "Không API", 0, "Pyramid shape cho regression."),
    Q("Performance test khác functional?", "Đo latency/throughput dưới load", "Cùng loại", "Chỉ manual", "Chỉ UI", 0, "Performance = non-functional."),
    Q("Security test (basic) trong API?", "AuthZ, injection, sensitive data leak", "Chỉ status 200", "Chỉ UI", "Không thuộc test", 0, "Security là loại test riêng nhưng hay gộp API."),
    Q("Smoke vs Sanity?", "Smoke: rộng shallow; Sanity: hẹp sau fix", "Giống nhau", "Ngược hoàn toàn", "Không dùng", 0, "Thuật ngữ hay nhầm — phỏng vấn hay hỏi."),
    Q("Test double là gì?", "Mock, stub, fake thay dependency", "Hai assertion", "Hai browser", "Hai CI", 0, "General term cho fake collaborators."),
    Q("E2E ít nhưng quan trọng vì?", "Chậm, flaky hơn nhưng bắt integration gap", "Không cần", "Thay unit", "Free", 0, "Ít E2E critical path, không bỏ hẳn."),
    Q("API regression sau deploy backend?", "Chạy trước/song song UI — fail sớm", "Không cần", "Chỉ manual", "Chỉ unit", 0, "API fail thường rẻ hơn để fix sớm."),
    Q("Component test (middle layer)?", "Giữa unit và E2E — module vài phần ghép", "Chỉ production", "Chỉ load", "Không tồn tại", 0, "Integration/component hay dùng interchangeably."),
    Q("Test data cho integration?", "Có thể DB test env, seed controlled", "Luôn production", "Không data", "Random only", 0, "Controlled test data giảm flaky."),
    Q("Shift-right (production monitoring)?", "Test/learn từ prod telemetry", "Thay unit test", "Chỉ manual", "Không liên quan", 0, "Bổ sung pyramid — observability."),
    Q("Negative testing API ví dụ?", "Invalid body → 400, wrong auth → 401", "Chỉ happy path 200", "Không assert status", "Chỉ UI", 0, "Negative = security/robustness."),
    Q("Unit test naming convention?", "method_condition_expected", "test1", "a", "Không tên", 0, "Tên rõ giúp debug CI fail."),
    Q("Khi nào ưu tiên API over UI automation?", "Service stable, UI đổi layout thường xuyên", "Luôn UI", "Không bao giờ API", "Chỉ manual", 0, "Layer chọn theo stability và ROI."),
    Q("4 loại test trong khóa — thứ tự execute CI điển hình?", "Unit → API/Integration → E2E smoke", "E2E trước unit", "Chỉ manual", "Random", 0, "Fail fast: rẻ trước, đắt sau."),
]

PHASE2 = [
    Q("WebDriver khác WebDriverManager?", "Driver = API; Manager tải driver binary phù hợp browser", "Giống nhau", "Manager thay Selenium", "Driver chỉ Firefox", 0, "Manager giải pain version chromedriver."),
    Q("By.id() ưu tiên vì?", "Thường unique, nhanh, ít brittle nhất", "Luôn chậm", "Bắt buộc XPath", "Không stable", 0, "Locator priority: id > name > css > xpath."),
    Q("XPath //button[@type='submit'] là?", "XPath tuyệt đối tìm button attribute", "CSS", "ID", "Link text", 0, "XPath mạnh nhưng dễ fragile nếu DOM sâu."),
    Q("Implicit wait 10s nghĩa là?", "Mỗi findElement chờ tối đa 10s nếu chưa có", "Chỉ một lần", "Chỉ explicit", "Không chờ", 0, "Implicit global — có thể làm test chậm nếu lạm dụng."),
    Q("Explicit wait WebDriverWait dùng?", "ExpectedCondition cụ thể (visible, clickable)", "Thread.sleep only", "Implicit only", "Không wait", 0, "Explicit = best practice chờ điều kiện."),
    Q("Thread.sleep trong test?", "Anti-pattern — flaky và lãng phí", "Best practice", "Thay explicit", "Bắt buộc", 0, "Hard sleep = không biết điều kiện thật."),
    Q("NoSuchElementException thường do?", "Locator sai hoặc element chưa xuất hiện", "Network down", "Java version", "TestNG", 0, "Fix: locator + wait + iframe."),
    Q("driver.findElement trả về?", "WebElement", "WebDriver", "List always", "String", 0, "Single element — findElements cho list."),
    Q("sendKeys vs click?", "sendKeys nhập text; click tương tác", "Giống nhau", "Ngược", "Không dùng", 0, "Basic interaction API."),
    Q("getAttribute('value') lấy?", "Giá trị attribute HTML (value, href...)", "Text visible", "CSS color", "Cookie", 0, "Attribute vs getText() khác nhau."),
    Q("switchTo().frame() khi nào?", "Element nằm trong iframe", "Mọi trang", "Sau alert", "Không cần", 0, "Phải switch context vào frame."),
    Q("Alert accept/dismiss dùng?", "driver.switchTo().alert()", "findElement By.id", "Actions only", "Javascript only", 0, "Alert là window riêng — switch alert."),
    Q("Actions class doubleClick dùng cho?", "Hover, drag-drop, double-click phức tạp", "Chỉ navigate", "Chỉ cookie", "Thay assert", 0, "Actions = low-level interaction chain."),
    Q("Page Object Model lợi ích?", "Tách locator/logic UI, reuse, maintain", "Chậm hơn", "Không OOP", "Thay TestNG", 0, "POM = design pattern cho Selenium."),
    Q("CSS selector #login-btn là?", "ID login-btn", "Class only", "XPath", "Name", 0, "# = id trong CSS selector."),
    Q("StaleElementReferenceException?", "Element DOM đã refresh, reference cũ invalid", "Locator sai", "Timeout", "Cookie", 0, "Re-find element sau navigation/refresh."),
    Q("Headless Chrome lợi ích CI?", "Chạy không UI, phù hợp server", "Không chạy được", "Chậm hơn luôn", "Không screenshot", 0, "Headless = CI standard."),
    Q("driver.get(url) vs navigate().to()?", "Cả hai mở URL — tương đương thực tế", "Khác hoàn toàn", "Chỉ get", "Chỉ navigate", 0, "get phổ biến; navigate part of Navigation interface."),
    Q("Screenshot on failure thường ở đâu?", "@AfterMethod listener / try-catch TestNG", "Trong @BeforeSuite only", "Không cần", "Manual only", 0, "Hook after test fail — phase4 sâu hơn."),
    Q("findElements size 0 nghĩa là?", "Không tìm thấy (empty list), không throw", "Exception luôn", "Tìm thấy một", "Bug Selenium", 0, "findElements an toàn khi có thể 0."),
]

PHASE3 = [
    Q("@Test trong TestNG?", "Đánh dấu method là test case", "Before suite", "Data provider only", "Listener", 0, "@Test = executable test method."),
    Q("@BeforeMethod chạy?", "Trước mỗi @Test method", "Một lần suite", "Sau test", "Không bao giờ", 0, "Setup per test — driver init thường ở đây."),
    Q("testng.xml dùng để?", "Khai báo suite, groups, parallel, listeners", "Viết locator", "Thay pom.xml", "Compile Java", 0, "XML điều khiển execution TestNG."),
    Q("@DataProvider trả về?", "Object[][] hoặc Iterator cho parameterized test", "String only", "void only", "WebDriver", 0, "Data-driven nhiều row data một test."),
    Q("dependsOnMethods?", "Test phụ thuộc test khác pass trước", "Parallel only", "Skip assert", "Group only", 0, "Order dependency — dùng cẩn thận."),
    Q("groups trong TestNG?", "Chạy subset smoke/regression", "Package name", "Maven profile only", "Không có", 0, "groups=smoke trên @Test và xml."),
    Q("POM: LoginPage extends BasePage lợi ích?", "Chia trách nhiệm từng trang", "Một class 5000 dòng", "Không cần driver", "Thay TestNG", 0, "Mỗi page một class — SRP."),
    Q("PageFactory @FindBy?", "Lazy init element khi dùng", "Eager only", "Thay driver", "Không Selenium", 0, "FindBy giảm boilerplate locator."),
    Q("Assert.assertEquals vs TestNG Assert?", "TestNG assert có message, integration report", "Không khác", "JUnit only", "Không assert", 0, "Assertions = verify expected."),
    Q("soft assert (SoftAssert)?", "Gom lỗi, assertAll() cuối", "Dừng ngay lỗi đầu", "Không TestNG", "Thay hard assert", 0, "Soft assert cho nhiều check một test."),
    Q("parallel='methods' trong xml?", "Chạy test methods song song", "Sequential only", "Chỉ class", "Không xml", 0, "Parallel cần thread-safe driver factory."),
    Q("@AfterMethod alwaysRun?", "Chạy cả khi test fail — quit driver", "Không chạy khi fail", "Chỉ pass", "Before test", 0, "Cleanup driver bắt buộc alwaysRun=true."),
    Q("InvocationCount=5?", "Chạy cùng test 5 lần", "5 thread", "5 browser", "5 suite", 0, "Dùng stress nhẹ hoặc flaky check."),
    Q("priority trong @Test?", "Thứ tự trong cùng class (không khuyến khích lạm dụng)", "Parallel level", "Group name", "Data row", 0, "priority thay dependsOn khi đơn giản."),
    Q("BaseTest chứa?", "driver setup/teardown, common config", "Tất cả locator app", "Production code", "Không nên", 0, "Base class DRY cho test infrastructure."),
    Q("Maven surefire + TestNG?", "Maven chạy TestNG khi mvn test", "Chỉ IDE", "Chỉ manual", "Không build", 0, "surefire plugin bind test phase."),
    Q("Listener onTestFailure?", "Screenshot, log, custom report", "Skip test", "Compile", "Data provider", 0, "Listener hook lifecycle TestNG."),
    Q("Page object không nên assert?", "Nên assert ở test layer; page trả state", "Assert trong mọi method", "Không assert bao giờ", "Chỉ trong xml", 0, "Debate: page có thể có isLoaded(); test quyết định pass."),
    Q("@Parameters đọc từ?", "testng.xml <parameter>", "application.properties only", "Env only", "Không hỗ trợ", 0, "XML parameters cho environment."),
    Q("RetryAnalyzer (preview phase4)?", "Tự chạy lại test fail", "Skip fail", "Double assert", "Không TestNG", 0, "Retry giảm flaky noise — config cẩn thận."),
]

PHASE4 = [
    Q("Listener ITestListener dùng?", "Hook pass/fail/skip events", "Locator", "Maven", "CSS", 0, "Listener = cross-cutting test behavior."),
    Q("Retry failed test risk?", "Che giấu bug thật nếu retry quá nhiều", "Luôn tốt", "Không retry được", "Chỉ manual", 0, "Retry có điều kiện + log."),
    Q("Cross-browser testing nghĩa?", "Chrome, Firefox, Edge — matrix", "Chỉ Chrome", "Chỉ headless", "Không Selenium", 0, "Grid/Cloud cho multi browser."),
    Q("Jenkins pipeline stage test?", "Build → Test → Deploy với gate", "Chỉ email", "Chỉ git", "Không CI", 0, "Pipeline as code — fail build nếu test fail."),
    Q("Screenshot file naming?", "timestamp_testName để unique", "fixed.png only", "Không lưu", "Chỉ log", 0, "Unique name tránh overwrite."),
    Q("Log4j/SLF4J trong framework?", "Structured log debug CI fail", "Thay assert", "Thay driver", "Không cần", 0, "Log + screenshot = triage nhanh."),
    Q("Flaky test mitigation?", "Explicit wait, stable locator, retry có kiểm soát", "sleep random", "Bỏ assert", "Chỉ chạy local", 0, "Flaky = địch CI ổn định."),
    Q("ThreadLocal WebDriver?", "Mỗi thread parallel có driver riêng", "Một driver global", "Không parallel", "Không Java", 0, "ThreadLocal pattern cho parallel TestNG."),
    Q("ExtentReport/Allure?", "HTML/report đẹp cho stakeholder", "Thay TestNG", "Thay Selenium", "Không report", 0, "Reporting = communication."),
    Q("Grid Selenium?", "Remote hub/node chạy browser từ xa", "Local only", "API only", "Không distribute", 0, "Grid scale browsers."),
    Q("Docker trong CI test?", "Consistent env, agent có browser image", "Thay Java", "Không cần", "Chỉ production", 0, "Container hóa test env."),
    Q("Failed test triage order?", "Log → screenshot → reproduce local", "Delete test", "Retry forever", "Ignore", 0, "Quy trình debug có hệ thống."),
    Q("@Factory trong TestNG?", "Tạo test instances dynamic", "Data provider", "Listener", "Maven", 0, "Factory advanced dynamic tests."),
    Q("Build pipeline fail on test?", "Quality gate — không deploy nếu đỏ", "Luôn deploy", "Không chạy test", "Chỉ warning", 0, "CI gate bảo vệ production."),
    Q("Environment variable trong CI?", "BASE_URL, CREDENTIALS từ Jenkins secrets", "Hardcode prod", "Không config", "Chỉ xml", 0, "Config externalized — 12-factor."),
    Q("Video recording test?", "Debug intermittent — tốn disk", "Bắt buộc", "Thay screenshot", "Không có tool", 0, "Video optional cho flaky E2E."),
    Q("Parallel classes vs methods?", "classes: mỗi class thread; methods: finer grain", "Giống nhau", "Không parallel", "Chỉ suite", 0, "Chọn parallel level theo isolation."),
    Q("Quarantine flaky tests?", "Tách suite unstable, fix riêng", "Xóa hết", "Retry vô hạn", "Không chạy CI", 0, "Quarantine giữ CI xanh trong khi fix."),
    Q("Definition CI vs CD?", "CI: integrate+test; CD: deploy automated", "Giống nhau", "Chỉ manual", "Chỉ unit", 0, "CI/CD hay đi cùng pipeline."),
    Q("Best practice secret trong repo?", "Không commit — dùng vault/env", "Commit cho tiện", "Hardcode OK", "Share chat", 0, "Security basics cho automation engineer."),
]

API1 = [
    Q("API là gì (interview)?", "Contract cho phép app giao tiếp qua request/response", "Chỉ website UI", "Chỉ database", "Chỉ JSON", 0, "API = interface giữa systems."),
    Q("REST stateless nghĩa?", "Mỗi request đủ context, server không nhớ session state", "Không HTTP", "Luôn cần cookie session", "Chỉ SOAP", 0, "Stateless = scale horizontal dễ."),
    Q("GET idempotent?", "Có — gọi nhiều lần không đổi resource (lý tưởng)", "Không", "Chỉ POST", "Luôn tạo mới", 0, "Idempotent quan trọng retry payment."),
    Q("POST tạo resource status thường?", "201 Created", "200 always", "404", "401", 0, "201 + Location header chuẩn REST."),
    Q("401 vs 403?", "401: chưa auth; 403: đã auth nhưng forbidden", "Giống nhau", "Ngược", "Không HTTP", 0, "Câu hỏi classic phỏng vấn API."),
    Q("404 khi nào?", "Resource/URL không tồn tại", "Auth fail", "Validation error", "Server crash", 0, "404 Not Found resource."),
    Q("400 Bad Request?", "Client gửi sai format/validation", "Server down", "Auth", "Success", 0, "400 = lỗi phía client payload."),
    Q("SOAP vs REST phỏng vấn?", "SOAP XML, contract chặt, enterprise; REST nhẹ JSON phổ biến", "REST dùng XML only", "SOAP nhanh hơn luôn", "Giống nhau", 0, "Biết context chọn protocol."),
    Q("GraphQL over-fetching giải quyết?", "Client chọn đúng fields cần", "Luôn lấy full table", "Chỉ SOAP", "Không query", 0, "GraphQL = flexible query, learning curve cao."),
    Q("Request header Authorization: Bearer?", "Gửi JWT/token", "Basic only", "Cookie only", "Không auth", 0, "Bearer token phổ biến REST."),
    Q("Response body validate ngoài status?", "Schema, business fields, DB state", "Chỉ status 200", "Chỉ time", "Không assert", 0, "API test 3 lớp: response, DB, side effect."),
    Q("Idempotency payment POST issue?", "Retry có thể double charge nếu không idempotency key", "Không vấn đề", "GET only", "Không test", 0, "POST không idempotent — design key quan trọng."),
    Q("PUT vs PATCH?", "PUT thay thế resource; PATCH partial update", "Giống nhau", "PATCH tạo mới", "PUT chỉ delete", 0, "PATCH cho update một phần."),
    Q("DELETE idempotent?", "Có — xóa lần 2 vẫn 'đã xóa' (404 hoặc 204)", "Không", "Tạo mới", "Chỉ POST", 0, "DELETE retry an toàn hơn POST create."),
    Q("DB verification sau POST user?", "SELECT confirm row exists, field đúng", "Chỉ trust API 201", "Không cần DB", "Chỉ UI", 0, "DB verify catch bug API 'fake success'."),
    Q("500 Internal Server Error?", "Lỗi server — log phía server", "Client typo", "Auth", "Not found", 0, "500 = triage backend/logs."),
    Q("Contract test benefit?", "Phát hiện breaking change API sớm", "Thay manual UI", "Không API", "Chỉ load", 0, "Consumer-driven contracts."),
    Q("Rate limit 429?", "Too Many Requests — cần backoff", "Auth fail", "OK", "Created", 0, "429 = throttle/quota."),
    Q("JSON Content-Type?", "application/json", "text/html", "multipart only", "soap+xml only", 0, "Header đúng cho REST JSON."),
    Q("Negative test SQL injection API?", "Payload malicious → không 500, reject/sanitize", "Chỉ happy path", "Không security", "Chỉ GET", 0, "Security negative là must-know."),
]

API2 = [
    Q("Authentication vs Authorization?", "AuthN: who are you; AuthZ: what you can do", "Giống nhau", "Ngược", "Không liên quan", 0, "Nhầm 401/403 thường từ nhầm hai khái niệm."),
    Q("Basic Auth encode?", "Base64(username:password) trong header", "Plain text header", "JWT only", "OAuth1 only", 0, "Basic đơn giản, HTTPS bắt buộc."),
    Q("JWT structure?", "header.payload.signature", "Chỉ JSON body", "SQL table", "Cookie only", 0, "JWT = signed claims."),
    Q("Bearer token gửi như?", "Authorization: Bearer <token>", "Body only", "Query only", "Footer HTML", 0, "Standard header format."),
    Q("Token expired test expect?", "401/403 + refresh flow nếu có", "200 OK", "201", "500 only", 0, "Negative auth critical."),
    Q("Role-based access test?", "User role A không gọi được API admin", "Chỉ login", "Chỉ UI", "Không negative", 0, "AuthZ matrix test cases."),
    Q("OAuth2 authorization code flow?", "Redirect login, exchange code for token", "Chỉ Basic", "Không token", "Chỉ SOAP", 0, "OAuth phổ biến third-party login."),
    Q("Session cookie vs JWT stateless?", "Session server-side state; JWT client holds", "Giống nhau", "JWT server session", "Cookie không HTTP", 0, "Tradeoff scale vs revoke."),
    Q("Brute force login API test?", "Lockout/rate limit sau N fail", "Unlimited try", "200 always", "Skip", 0, "Security requirement thực tế."),
    Q("Horizontal privilege escalation?", "User A access data user B cùng role", "Vertical admin", "SQL only", "UI only", 0, "IDOR hay gặp — test với 2 user."),
    Q("Vertical privilege?", "User thường gọi API admin", "Same user data", "GET only", "Cookie size", 0, "403 expected cho user thường."),
    Q("HTTPS why?", "Encrypt transit, protect token/password", "Faster", "Required JSON", "Optional always", 0, "Không test auth trên HTTP production."),
    Q("API key in query string risk?", "Leak log/referrer — prefer header", "Best practice", "Most secure", "Required", 0, "Security review hay chỉ ra."),
    Q("Refresh token purpose?", "Lấy access token mới không re-login", "Delete user", "Patch only", "DB only", 0, "Refresh flow test riêng."),
    Q("CORS error thường ở?", "Browser cross-origin — không phải Postman", "Server down", "DB", "JUnit", 0, "Postman bypass CORS — hiểu browser vs API tool."),
    Q("Sensitive data in response?", "Không trả password hash, full PAN", "Trả hết cho debug", "OK production", "Chỉ UI", 0, "Data minimization security."),
    Q("Multi-tenant auth test?", "Tenant A token không access tenant B data", "Single user", "No header", "Skip DB", 0, "SaaS critical scenario."),
    Q("Logout invalidate token?", "Token cũ không dùng được", "Token forever", "200 only", "No test", 0, "Revocation/blacklist test."),
    Q("MFA API flow test?", "Step password + OTP", "Single step only", "No negative", "UI only", 0, "Multi-step auth automation."),
    Q("Security header HSTS?", "Force HTTPS browser", "JWT sign", "CORS", "JSON schema", 0, "Ops/security awareness cho tester."),
]

API3 = [
    Q("RestAssured given().when().then()?", "Arrange request, act call, assert response", "Chỉ assert", "Chỉ UI", "Chỉ SQL", 0, "BDD style API test RA."),
    Q("given().baseUri() set?", "Base URL API", "Database", "Browser", "TestNG xml only", 0, "baseUri + path = full URL."),
    Q(".statusCode(200) trong then()?", "Assert HTTP status", "Assert body only", "Header only", "Time only", 0, "Status assert cơ bản."),
    Q(".body(\"name\", equalTo(\"x\"))?", "JsonPath assert field", "XPath UI", "SQL", "CSS", 0, "Hamcrest matchers trong RA."),
    Q("POST with body JSON?", "given().contentType(JSON).body(obj).when().post()", "Chỉ GET", "Chỉ delete", "Không body", 0, "Serialization object/map to JSON."),
    Q("extract().path(\"id\") dùng?", "Lấy value chain request sau", "Screenshot", "Driver quit", "Compile", 0, "Chaining create → get by id."),
    Q("RequestSpec reuse?", "given(requestSpec) DRY headers/auth", "Copy paste mọi test", "Không RA", "UI POM only", 0, "Spec builder pattern RA."),
    Q("ResponseSpec validate chung?", "expect status, contentType chung mọi test", "Mỗi test khác hẳn", "Không assert", "Manual only", 0, "ResponseSpec = shared assertions."),
    Q("log().all() khi debug?", "In request/response detail", "Production always", "Thay assert", "Delete test", 0, "Log verbose khi triage fail."),
    Q("TestNG @BeforeClass API setup?", "Base URI, auth token once per class", "Mỗi assert", "Không setup", "UI only", 0, "Fixture pattern RA + TestNG."),
    Q("DataProvider + RestAssured?", "Nhiều row data gọi cùng test logic", "Không data-driven", "Chỉ manual", "Chỉ CSV UI", 0, "Combine TestNG data + RA."),
    Q("API Page Object?", "Class UsersApi với methods getUser(), createUser()", "Locator By.id", "Driver only", "Không POM", 0, "POM concept áp API layer."),
    Q("BaseTest chứa spec/auth?", "requestSpec, token refresh helper", "Tất cả test logic", "Production app code", "Không nên", 0, "BaseTest infrastructure RA."),
    Q("Schema validation RA?", "body(matchesJsonSchemaInClasspath)", "Chỉ status", "Chỉ UI", "Không JSON", 0, "Contract schema validation."),
    Q("Query param given().queryParam()?", "Thêm ?key=value URL", "Body only", "Header only", "Cookie only", 0, "Query vs path vs body params."),
    Q("Path param get(\"/users/{id}\", id)?", "URL template variable", "Query only", "Header only", "SOAP only", 0, "Path param RESTful resource id."),
    Q("Authentication RA preemptive Basic?", "given().auth().preemptive().basic(user, pass)", "Không auth RA", "UI login only", "Manual only", 0, "RA hỗ trợ auth helpers."),
    Q("Parallel TestNG + RA lưu ý?", "Test independent, không share mutable state", "Shared static token unsafe", "One thread only", "No data", 0, "Thread safety khi parallel API tests."),
    Q("Allure + RestAssured?", "Attach request/response vào report", "Thay TestNG", "Thay RA", "Không report", 0, "Reporting stakeholder-friendly."),
    Q("Interview: RA vs Postman?", "RA = code, CI, version control; Postman = explore/manual", "Giống hẳn", "Postman CI better always", "RA không code", 0, "Biết khi nào tool nào — senior answer."),
]
